# @package _global_

model:
  n_layer: 12
  n_head: 12
  n_embd: 768
  use_scaling: 0
  
  gpt:
    _target_: models.gpt.GPT
    mixing_layer: ${model.mixing_layer}
    vocab_size: ${model.vocab_size}
    n_layer: ${model.n_layer}
    n_head: ${model.n_head}
    n_embd: ${model.n_embd}
    use_scaling: ${model.use_scaling}
    use_nGPT: 0
    use_attn_alpha: 0
    use_attn_mlp: 0
    use_suv: 0
    log_stats: 0
